package:
  name: tk_plot_utils
  version: 0.1.0

build:
  number: 1

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - jupyter
    - plotly

test:
  requires:
    - numpy
  source_files:
    - examples

about:
  summary: Personal functions to use Python's plotting libraries more easily
  license_file: LICENSE
