package:
  name: tk_plot_utils
  version: 0.8.1

build:
  number: 1

source:
  git_url: ../

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - jupyter
    - numpy
    - plotly

test:
  source_files:
    - examples

about:
  summary: Personal functions to use Python's plotting libraries more easily
  license_file: LICENSE
